BACKUP DATABASE [BACKUPTEST] TO  DISK = N'F:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\BACKUPTEST.bak' 
WITH NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO
