BACKUP LOG [BACKUPTEST] TO  DISK = N'F:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\TLOG5.BAK' 
WITH NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, NO_COMPRESSION,  STATS = 10
GO
