--AHMET ÖMER'E 1.000 TL PARA GÖNDERÝYOR.
INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES
(1, 2, 1000, '20200414 14:21:36', 'TL', '12345678', ' ')

UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE-1000
WHERE ACCOUNTID=1

INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES
(2, 1, 1000, '20200414 15:21:36', 'TL', '1234567', '0987654321')

UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE+1000
WHERE ACCOUNTID=2

SELECT C.CUSTOMERNAME, A.ACCOUNTNO, A.ACCOUNTNAME, A.CURRENCY, B.BALANCE FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID=B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID=A.CUSTOMERID

----------------------------------------------------------------------------------------------------------

--Peki zincirin herhangi bir yerinde bir hata cikarsa?

TRUNCATE TABLE MONEYTRANSACTIONS

UPDATE ACCOUNTBALANCE SET BALANCE=1000 WHERE ACCOUNTID=1
UPDATE ACCOUNTBALANCE SET BALANCE=0 WHERE ACCOUNTID=2


BEGIN TRAN --transaction islemi basladi
INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES
(1, 2, 1000, '20200414 14:21:36', 'TL', '12345678', ' ')
IF @@ERROR > 0
BEGIN
	ROLLBACK TRAN --islemi geri al
	RETURN
END

UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE-1000
WHERE ACCOUNTID=1
IF @@ERROR > 0
BEGIN
	ROLLBACK TRAN --islemi geri al
	RETURN
END


INSERT INTO MONEYTRANSACTIONS
(ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES
(2, 1, 1000, '20200414 15:21:36', 'TL', '1234567', 'abcdefghasd0987654321')
IF @@ERROR > 0 --Hata verecek, EFTCODE2 10 karakterden uzun olmamali.
BEGIN
	ROLLBACK TRAN --islemi geri al
	RETURN
END


UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE+1000
WHERE ACCOUNTID=2
IF @@ERROR > 0
BEGIN
	ROLLBACK TRAN --islemi geri al
	RETURN
END

COMMIT TRAN --islemi gerceklestir.
--Bu adima kadar islem LDF dosyasinda tutulur.
--COMMIT TRAN sonrasinda MDF dosyasina aktarilir.

---------------------------------------------------------------------------------------


